#!/bin/bash
# Replace Kitty's custom icon and flush the icon cache.
# Usage: ./reload-icon.sh

ICON="$(dirname "$0")/kitty.app.icns"
APP="/Applications/kitty.app"

if [ ! -f "$ICON" ]; then
  echo "Icon not found: $ICON"
  exit 1
fi

sudo fileicon set "$APP" "$ICON"

# Flush icon caches (auto-regenerated by macOS; rm -rf is safe here)
sudo rm -rf /Library/Caches/com.apple.iconservices.store
sudo find /private/var/folders -maxdepth 3 -name "com.apple.iconservices" -exec rm -rf {} + 2>/dev/null
sudo killall -KILL iconservicesagent 2>/dev/null
killall Finder
killall Dock

echo "Icon set."
